#spring:
#  application:
#    name: APIGATEWAY
#
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        - id: USERSERVICE
#          uri: lb://USERSERVICE
#          predicates:
#            - Path=/api/**
#        - id: RATINGSERVICE
#          uri: lb://RATINGSERVICE
#          predicates:
#            - Path=/ratings/**
#        - id: HOTELSERVICE
#          uri: lb://HOTELSERVICE
#          predicates:
#            - Path=/hotels/**
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: true
#    fetch-registry: true
#  instance:
#    prefer-ip-address: true
#
#server:
#  port: 9094
